### ISSUE TITLE
Cannot build sqlite3 and serial port on RPi

### ISSUE THREAD

**Issue by solshark** [mapbox/node-pre-gyp#132]
```
pi@raspberrypi /data/www/aquacontroller-04-01-2015-22:08:53 $ npm install sqlite3
|
> sqlite3@3.0.4 install /data/www/aquacontroller-04-01-2015-22:08:53/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

make: Entering directory '/data/www/aquacontroller-04-01-2015-22:08:53/node_modules/sqlite3/build'
action_after_build.target.mk:6: *** target pattern contains no '%'.  Stop.
make: Leaving directory '/data/www/aquacontroller-04-01-2015-22:08:53/node_modules/sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.18.1+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=3.0.4" "--major=3" "--patch=4" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--target_platform=linux" "--arch=arm" "--target_arch=arm" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/data/www/aquacontroller-04-01-2015-22:08:53/node_modules/sqlite3/lib/binding/node-v11-linux-arm" "--module=/data/www/aquacontroller-04-01-2015-22:08:53/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node" "--remote_path=./sqlite3/v3.0.4/" "--package_name=node-v11-linux-arm.tar.gz" "--staged_tarball=build/stage/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz"
gyp ERR! cwd /data/www/aquacontroller-04-01-2015-22:08:53/node_modules/sqlite3
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/data/www/aquacontroller-04-01-2015-22:08:53/node_modules/sqlite3/lib/binding/node-v11-linux-arm --module=/data/www/aquacontroller-04-01-2015-22:08:53/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-v11-linux-arm.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 3.18.1+
node-pre-gyp ERR! command "node" "/usr/local/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /data/www/aquacontroller-04-01-2015-22:08:53/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.10.35
node-pre-gyp ERR! node-pre-gyp -v v0.6.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node --node_abi=node-v11 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/data/www/aquacontroller-04-01-2015-22:08:53/node_modules/sqlite3/lib/binding/node-v11-linux-arm --module=/data/www/aquacontroller-04-01-2015-22:08:53/node_modules/sqlite3/lib/binding/node-v11-linux-arm/node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-v11-linux-arm.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v11-linux-arm.tar.gz' (1)

npm ERR! sqlite3@3.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.4 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.18.1+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3"
npm ERR! cwd /data/www/aquacontroller-04-01-2015-22:08:53
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
pi@raspberrypi /data/www/aquacontroller-04-01-20
```

```
pi@raspberrypi ~ $ node --version
v0.10.35
pi@raspberrypi ~ $ npm --version
1.4.28
pi@raspberrypi ~ $ node-pre-gyp --version
v0.6.1
```

**Comment by solshark** [comment]
Updated system using apt-get upgrade and now it works. Unfortunately, have no idea what was the issue - list of updated packages unavailable now.

**Comment by TomFreudenberg** [comment]
This might be an equal issue to https://github.com/mapbox/node-sqlite3/issues/671 - reported release here also (faulty release) v0.6.4
