### ISSUE TITLE
EBUSY errors causing failing tests on windows

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-pre-gyp#139]
Not sure if this is a fluke or a deeper problem. Logging here for taking a look at later:

```
 1) build app1 builds :
     Error: timeout of 100000ms exceeded
      at null.<anonymous> (c:\projects\node-pre-gyp\node_modules\mocha\lib\runnable.js:158:19)
      at Timer.listOnTimeout (timers.js:133:15)
  2) build app1 builds with custom --target=0.11.12 that is greater than known version in ABI crosswalk :
     Uncaught Error: Command failed: cmd.exe /s /c "node-pre-gyp rebuild --fallback-to-build --target=0.11.12 -C c:\projects\node-pre-gyp\test\app1 --msvs_version=2013  "
gyp ERR! clean error 
gyp ERR! stack Error: EBUSY, unlink 'c:\projects\node-pre-gyp\test\app1\build'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 6.2.9200
```

https://ci.appveyor.com/project/Mapbox/node-pre-gyp/build/job/n4vnvvgvybuv82kt

**Comment by springmeyer** [comment]
not seen recently, closing.
