### ISSUE TITLE
node-gyp not found on mac

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-pre-gyp#156]
Seen with node v0.10.30 installed via homebrew on @aaronlidman's system. The spawn to `node-gyp` failed. We worked around the problem by doing `npm install -g node-gyp`.

Similiar to #126 - needs a close look. see also #151

**Comment by springmeyer** [comment]
@aaronlidman - please add any more detail if you think of anything custom about your node install - perhaps you have numerous node versions installed with homebrew?

**Comment by aaronlidman** [comment]
I don't think I'm doing anything special. Here's the relevant section if it helps:
```js
success: now run 'npm install --build-from-source'
nan@1.6.2 node_modules/nan

mocha@2.2.4 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.1
├── diff@1.0.8
├── growl@1.8.1
├── commander@2.3.0
├── debug@2.0.0 (ms@0.6.2)
├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
└── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)

aws-sdk@2.1.24 node_modules/aws-sdk
├── xmlbuilder@0.4.2
├── xml2js@0.2.8
└── sax@0.5.3

node-pre-gyp@0.6.4 node_modules/node-pre-gyp
source ./bootstrap.sh && ./node_modules/.bin/node-pre-gyp configure --loglevel=error --clang=1
success: now run 'npm install --build-from-source'
node-pre-gyp ERR! configure error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp configure --loglevel=error --clang=1 --module=/Users/aaron/node-osrm-test/lib/binding/osrm.node --module_name=osrm --module_path=/Users/aaron/node-osrm-test/lib/binding' (Error: spawn ENOENT)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/aaron/node-osrm-test/node_modules/node-pre-gyp/lib/util/compile.js:67:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:95:17)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:808:12)
node-pre-gyp ERR! System Darwin 13.4.0
node-pre-gyp ERR! command "node" "/Users/aaron/node-osrm-test/node_modules/.bin/node-pre-gyp" "configure" "--loglevel=error" "--clang=1"
node-pre-gyp ERR! cwd /Users/aaron/node-osrm-test
node-pre-gyp ERR! node -v v0.10.30
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp configure --loglevel=error --clang=1 --module=/Users/aaron/node-osrm-test/lib/binding/osrm.node --module_name=osrm --module_path=/Users/aaron/node-osrm-test/lib/binding' (Error: spawn ENOENT)
make: *** [build] Error 1
```
