### ISSUE TITLE
Build Failure: node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by alukach** [mapbox/node-pre-gyp#178]
I'm experiencing a build failure appears to be similar to mapbox/node-sqlite3#481 and some other issues on that repo.  This began when I upgraded to Node 4.1.2.  See below:

``` bash
$ npm install mbtiles
npm WARN package.json tile-uploader@1.0.0 No README data
npm WARN engine tiletype@0.1.0: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.1.2","npm":"2.14.6"})
Release/obj/gen/sqlite-autoconf-3081101/sqlite3.c:9117:26: warning: unused variable 'sqlite3one'
      [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
1 warning generated.
In file included from ../src/database.cc:5:
In file included from ../src/database.h:11:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/anthony/.node-gyp/4.1.2/include/node/node_buffer.h:31:40: note: candidate function not viable: no known
      conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/anthony/.node-gyp/4.1.2/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument
      ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/anthony/.node-gyp/4.1.2/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/anthony/.node-gyp/4.1.2/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/database.cc:5:
In file included from ../src/database.h:11:
../node_modules/nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to
      'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/anthony/.node-gyp/4.1.2/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor)
      not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st
      argument
class Local {
      ^
/Users/anthony/.node-gyp/4.1.2/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor)
      not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/anthony/.node-gyp/4.1.2/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local'
      against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/anthony/.node-gyp/4.1.2/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *'
      against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/database.cc:5:
In file included from ../src/database.h:11:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../src/database.cc:145:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:230:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:509:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:610:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
In file included from ../src/database.cc:2:
In file included from /Users/anthony/.node-gyp/4.1.2/include/node/node.h:42:
/Users/anthony/.node-gyp/4.1.2/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from
      incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/anthony/.node-gyp/4.1.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template specialization
      'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/database.cc:2:
In file included from /Users/anthony/.node-gyp/4.1.2/include/node/node.h:42:
/Users/anthony/.node-gyp/4.1.2/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/anthony/.node-gyp/4.1.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template specialization
      'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/database.cc:2:
In file included from /Users/anthony/.node-gyp/4.1.2/include/node/node.h:42:
/Users/anthony/.node-gyp/4.1.2/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/anthony/.node-gyp/4.1.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization
      'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/database.cc:2:
In file included from /Users/anthony/.node-gyp/4.1.2/include/node/node.h:42:
/Users/anthony/.node-gyp/4.1.2/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/anthony/.node-gyp/4.1.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization
      'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
4 warnings and 9 errors generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/anthony/Projects/map-experiments/ocean-tileset/tile-uploader/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/Cellar/node/4.1.2/bin/node" "/Users/anthony/Projects/map-experiments/ocean-tileset/tile-uploader/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/anthony/Projects/map-experiments/ocean-tileset/tile-uploader/node_modules/mbtiles/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/anthony/Projects/map-experiments/ocean-tileset/tile-uploader/node_modules/mbtiles/node_modules/sqlite3/lib/binding/node-v46-darwin-x64"
gyp ERR! cwd /Users/anthony/Projects/map-experiments/ocean-tileset/tile-uploader/node_modules/mbtiles/node_modules/sqlite3
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/4.1.2/bin/node /Users/anthony/Projects/map-experiments/ocean-tileset/tile-uploader/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/anthony/Projects/map-experiments/ocean-tileset/tile-uploader/node_modules/mbtiles/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/anthony/Projects/map-experiments/ocean-tileset/tile-uploader/node_modules/mbtiles/node_modules/sqlite3/lib/binding/node-v46-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/anthony/Projects/map-experiments/ocean-tileset/tile-uploader/node_modules/mbtiles/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 14.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/4.1.2/bin/node" "/Users/anthony/Projects/map-experiments/ocean-tileset/tile-uploader/node_modules/mbtiles/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/anthony/Projects/map-experiments/ocean-tileset/tile-uploader/node_modules/mbtiles/node_modules/sqlite3
node-pre-gyp ERR! node -v v4.1.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/Cellar/node/4.1.2/bin/node" "/usr/local/bin/npm" "install" "mbtiles"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.6
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.10 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/anthony/Projects/map-experiments/ocean-tileset/tile-uploader/npm-debug.log
```

My `npm-debug.log` file can be found [here](https://gist.github.com/alukach/16ea3d23d41da4fb8617). Any thoughts? I my version of Node unsupported?

Thanks.

---

**Edit:** I now see that the docs state:

> Node.js 0.12.x -> 0.8.x

Downgraded to `0.12.7` and all is well. Will leave this open for comment, but feel free to close.

**Comment by springmeyer** [comment]
To support Node 4x you need at least node-sqlite3 3.1.x (you have 3.0.x).

**Comment by Arieg419** [comment]
Hi,

I had the same "Build Failure: node-pre-gyp install --fallback-to-build" issue. 

Instead of running npm install sqlite3@3.0.10 --save, I ran npm install sqlite3 --save, allowing npm to grab the newest updated version.

Now it works :) I thing @springmeyer is right, and its an issue caused by your node version.

I am running v6.4.0.

Cheers,
Omer
