### ISSUE TITLE
node-pre-gyp install fails when compiling fsevents on OSX

### ISSUE THREAD

**Issue by denysvitali** [mapbox/node-pre-gyp#200]
As per [fsevents/#122](https://github.com/strongloop/fsevents/issues/122) I'm crossposting the issue here since I don't understand if it's a node-pre-gyp problem or a fsevents.

The latest build I tried is in the [latest comment of the issue](https://github.com/strongloop/fsevents/issues/122#issuecomment-204302421)
The error thrown is:
```
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.34.2
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/username/Desktop/myApp/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:156:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/username/Desktop/myApp/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:277:19)
node-pre-gyp ERR! stack     at install (/Users/username/Desktop/myApp/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/username/Desktop/myApp/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/username/Desktop/myApp/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/username/Desktop/myApp/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:413:34)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:422:10)
node-pre-gyp ERR! stack     at Module.load (module.js:357:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:314:12)
node-pre-gyp ERR! System Darwin 15.4.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/username/Desktop/myApp/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/username/Desktop/myApp/node_modules/fsevents
node-pre-gyp ERR! node -v v5.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok
```

**Comment by springmeyer** [comment]
closing as invalid. this is not replicable: https://github.com/strongloop/fsevents/issues/122#issuecomment-209469669
