### ISSUE TITLE
fseventsnode-pre-gyp install error

### ISSUE THREAD

**Issue by Luncher** [mapbox/node-pre-gyp#208]
mac : 10.11.4

my project use the fsevent module When I compile electron app, the following error:
> fsevents@1.0.11 install /Users/jim/work/LocalHolaStudio/release/app/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack TypeError: Cannot read property 'major' of null
node-pre-gyp ERR! stack     at get_electron_abi (/Users/jim/work/LocalHolaStudio/release/app/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:30:36)
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/jim/work/LocalHolaStudio/release/app/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:73:16)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/jim/work/LocalHolaStudio/release/app/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:277:19)
node-pre-gyp ERR! stack     at install (/Users/jim/work/LocalHolaStudio/release/app/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/jim/work/LocalHolaStudio/release/app/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/jim/work/LocalHolaStudio/release/app/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/jim/work/LocalHolaStudio/release/app/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:413:34)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:422:10)
node-pre-gyp ERR! stack     at Module.load (module.js:357:32)
node-pre-gyp ERR! System Darwin 15.4.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/jim/work/LocalHolaStudio/release/app/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jim/work/LocalHolaStudio/release/app/node_modules/fsevents
node-pre-gyp ERR! node -v v5.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok 
Cannot read property 'major' of null

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "rebuild" "--production"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.11 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1

**Comment by antoinerousseau** [comment]
how did you solve this?

**Comment by Luncher** [comment]
not resolved yet
