### ISSUE TITLE
{node_abi}-{platform}-{arch}.tar.gz filename format doesn't work with SunOS/Solaris/SmartOS/OmniOS

### ISSUE THREAD

**Issue by dekobon** [mapbox/node-pre-gyp#251]
Due to an unfortunate history of the SunOS derivative operating systems. The `uname -s` (kernel name / platform name) returned on Solaris family operating systems all return SunOS. The reality is that you would be hard-pressed to find a SunOS box to do a build on in order to create a binary that was compatible with Solaris 11 / OpenSolaris / SmartOS / Illumos / OmniOS, etc.

Would there be a way to add an additional field of information like distro or kernel version to allow binaries to be distinguished further? As it stands now, making downloadable binaries for the OpenSolaris derivative OSes is impossible to do an a way that is universally compatible.

In fact, this may be a problem with Linux as well. Even though the Linux system call table remains fairly stable, there have been breaking changes from time to time and there is no guarantee that there will not be in the future, so capturing another metric to indicate the api compatibility level of the kernel would be a good idea.

**Comment by vernak2539** [comment]
I believe this is the same issue I'm having.

We're using x64 CentOS 7 boxes. Some of the error log is below
```
[10:38:30][npm install] > fsevents@1.0.15 install /opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents
[10:38:30][npm install] > node-pre-gyp install --fallback-to-build
[10:38:30][npm install] 
[10:38:31][npm install] node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.15/fse-v1.0.15-node-v48-linux-x64.tar.gz 
[10:38:31][npm install] node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.15 and node@6.5.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
[10:38:31][npm install] gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
[10:38:32][npm install] gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
[10:38:32][npm install] gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
[10:38:32][npm install] make: Entering directory `/opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents/build'
[10:38:32][npm install]   SOLINK_MODULE(target) Release/obj.target/.node
[10:38:32][npm install] make: Leaving directory `/opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents/build'
[10:38:32][npm install] make: g++: Command not found
[10:38:32][npm install] make: *** [Release/obj.target/.node] Error 127
[10:38:32][npm install] gyp ERR! build error 
[10:38:32][npm install] gyp ERR! stack Error: `make` failed with exit code: 2
[10:38:32][npm install] gyp ERR! stack     at ChildProcess.onExit (/opt/teamcity_1/system/jonnyzzz.nvm/v6.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
[10:38:32][npm install] gyp ERR! stack     at emitTwo (events.js:106:13)
[10:38:32][npm install] gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
[10:38:32][npm install] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[10:38:32][npm install] gyp ERR! System Linux 3.10.0-327.36.2.el7.x86_64
[10:38:32][npm install] gyp ERR! command "/opt/teamcity_1/system/jonnyzzz.nvm/v6.5.0/bin/node" "/opt/teamcity_1/system/jonnyzzz.nvm/v6.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents/lib/binding/Release/node-v48-linux-x64/fse.node" "--module_name=fse" "--module_path=/opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents/lib/binding/Release/node-v48-linux-x64"
[10:38:32][npm install] gyp ERR! cwd /opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents
[10:38:32][npm install] gyp ERR! node -v v6.5.0
[10:38:32][npm install] gyp ERR! node-gyp -v v3.3.1
[10:38:32][npm install] gyp ERR! not ok 
[10:38:32][npm install] node-pre-gyp ERR! build error 
[10:38:32][npm install] node-pre-gyp ERR! stack Error: Failed to execute '/opt/teamcity_1/system/jonnyzzz.nvm/v6.5.0/bin/node /opt/teamcity_1/system/jonnyzzz.nvm/v6.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents/lib/binding/Release/node-v48-linux-x64/fse.node --module_name=fse --module_path=/opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents/lib/binding/Release/node-v48-linux-x64' (1)
[10:38:32][npm install] node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
[10:38:32][npm install] node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
[10:38:32][npm install] node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
[10:38:32][npm install] node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
[10:38:32][npm install] node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[10:38:32][npm install] node-pre-gyp ERR! System Linux 3.10.0-327.36.2.el7.x86_64
[10:38:32][npm install] node-pre-gyp ERR! command "/opt/teamcity_1/system/jonnyzzz.nvm/v6.5.0/bin/node" "/opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
[10:38:32][npm install] node-pre-gyp ERR! cwd /opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents
[10:38:32][npm install] node-pre-gyp ERR! node -v v6.5.0
[10:38:32][npm install] node-pre-gyp ERR! node-pre-gyp -v v0.6.29
[10:38:32][npm install] node-pre-gyp ERR! not ok 
[10:38:32][npm install] Failed to execute '/opt/teamcity_1/system/jonnyzzz.nvm/v6.5.0/bin/node /opt/teamcity_1/system/jonnyzzz.nvm/v6.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents/lib/binding/Release/node-v48-linux-x64/fse.node --module_name=fse --module_path=/opt/teamcity_1/work/867b3a477a07a47e/node_modules/fsevents/lib/binding/Release/node-v48-linux-x64' (1)
```

**Comment by Mithgol** [comment]
Do you have some exact idea of a better identifier in mind?

**Comment by Mithgol** [comment]
(I get it that `package_name` should allow something like `{node_abi}-{platform}-{kernelid}-{arch}.tar.gz` instead of a simpler `{node_abi}-{platform}-{arch}.tar.gz`, but what exactly would that `{kernelid}` be?)

**Comment by Mithgol** [comment]
Ideally, and in the future, if a good enough kernel identifier works well on the node-pre-gyp level, then it should be further proposed to Node.js developers as a new feature, a new field of Node's `process` object.

**Comment by xzyfer** [comment]
We (the node-sass team) ran into a similar issue trying to support Alpine. It reports itself as linux but doesn't always work with typical `glibc` binaries.

We ended up with `{platform}_{platformvariant}-{arch}-{abiversion}_binding` where `platformvariant` was `musl` on Alpine.

https://github.com/sass/node-sass/pull/1836

**Comment by saper** [comment]
We can have different libc ABIs (`glibc2` vs `musl`), different stdc++ ABIs (clang vs GNU vs various versions of Visual Studio) and of course node ABI that includes V8. Additionally there are problems with bundled/unbundled OpenSSL and libuv, but that would be a real can of worms...
