### ISSUE TITLE
Error: Unknown Runtime: 'electron' when building `thread-sleep@1.0.4` for Electron

### ISSUE THREAD

**Issue by jviotti** [mapbox/node-pre-gyp#281]
I'm facing weird error when building `thread-sleep@1.0.4` for the Electron runtime. I have other dependencies in my project that use `node-pre-gyp` (like `lzma-native`) that work fine, however `thread-sleep` refuses to build if I set `npm_config_runtime=electron`. 

I managed to reduce the problem to the following set of commands, which I'm running in macOS 10.12.4, even though the issue seems to happen everywhere:

```js
export npm_config_disturl=https://atom.io/download/electron
export npm_config_arch=x64
export npm_config_runtime=electron
export npm_config_target=1.4.4
export npm_config_build_from_source=true

npm install --save thread-sleep@1.0.4
```

Running the above commands results in:

```
> thread-sleep@1.0.4 install /Users/jviotti/Projects/playground/foo/node_modules/thread-sleep
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: Unknown Runtime: 'electron'
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/jviotti/Projects/playground/foo/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/util/versioning.js:60:19)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/jviotti/Projects/playground/foo/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at handle_gyp_opts (/Users/jviotti/Projects/playground/foo/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/util/handle_gyp_opts.js:54:27)
node-pre-gyp ERR! stack     at configure (/Users/jviotti/Projects/playground/foo/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/configure.js:11:5)
node-pre-gyp ERR! stack     at /Users/jviotti/Projects/playground/foo/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/build.js:35:13
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jviotti/Projects/playground/foo/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/util/compile.js:85:9)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Darwin 16.5.0
node-pre-gyp ERR! command "/Users/jviotti/.nvm/versions/node/v6.1.0/bin/node" "/Users/jviotti/Projects/playground/foo/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jviotti/Projects/playground/foo/node_modules/thread-sleep
node-pre-gyp ERR! node -v v6.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/jviotti/.nvm/versions/node/v6.1.0/bin/node" "/Users/jviotti/.nvm/versions/node/v6.1.0/bin/npm" "install" "--save" "thread-sleep@1.0.4"
npm ERR! node v6.1.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! thread-sleep@1.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the thread-sleep@1.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thread-sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thread-sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thread-sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jviotti/Projects/playground/foo/npm-debug.log
```

How come the `electron` runtime is unknown given that the same `node-pre-gyp` version is successfully building other modules?

**Comment by jviotti** [comment]
BTW, removing `node_modules` and installing again, as recommended by https://github.com/electron/electron-rebuild/issues/25, doesn't make a difference.

**Comment by jviotti** [comment]
> When installing fsevents, i don't get the last node-pre-gyp release but the 0.6.11 which does not support Electron.

Oh, `thread-sleep` seems to be using its own bundled `node-pre-gyp` version, v0.6.9, which as implied on that message, doesn't support Electron.

**Comment by jviotti** [comment]
That indeed turned out to be the issue. Thanks a lot!
