### ISSUE TITLE
sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`

### ISSUE THREAD

**Issue by jester22** [mapbox/node-pre-gyp#293]
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.34.2
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/jester/Workspaces/ReactNativeWorkspace/my-project/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js:156:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/jester/Workspaces/ReactNativeWorkspace/my-project/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js:277:19)
node-pre-gyp ERR! stack     at handle_gyp_opts (/Users/jester/Workspaces/ReactNativeWorkspace/my-project/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/handle_gyp_opts.js:54:27)
node-pre-gyp ERR! stack     at configure (/Users/jester/Workspaces/ReactNativeWorkspace/my-project/node_modules/sqlite3/node_modules/node-pre-gyp/lib/configure.js:11:5)
node-pre-gyp ERR! stack     at /Users/jester/Workspaces/ReactNativeWorkspace/my-project/node_modules/sqlite3/node_modules/node-pre-gyp/lib/build.js:35:13
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jester/Workspaces/ReactNativeWorkspace/my-project/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:85:9)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 16.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/jester/Workspaces/ReactNativeWorkspace/my-project/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jester/Workspaces/ReactNativeWorkspace/my-project/node_modules/sqlite3
node-pre-gyp ERR! node -v v6.10.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN lottie-react-native@1.1.1 requires a peer of react@>=15.3.1 but none was installed.
npm WARN react-native-maps@0.12.2 requires a peer of react@>=15.4.0 but none was installed.
npm WARN react-native-svg@4.4.1 requires a peer of react@>=15.4.0 but none was installed.
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the sqlite3@3.1.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by nathanaelg16** [comment]
Same error on Ubuntu 16.04.02 x64
System Linux 4.4.0-81-generic
node: v6.11.1-nightly20170607f7ca483d68
node-pre-gyp: v0.6.36
npm: v5.0.3

**Comment by thisdoug** [comment]
Same issue
OSX 1.7.5
Darwin 11.4.2
node v8.7.0
node-pre-gyp v0.5.22
npm 5.4.2

```bash
node-pre-gyp info using node-pre-gyp@0.5.22
node-pre-gyp info using node@8.7.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: Cannot find module 'internal/errors'
node-pre-gyp ERR! stack     at Function.Module._resolveFilename (module.js:527:15)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:476:23)
node-pre-gyp ERR! stack     at Module.require (module.js:568:17)
node-pre-gyp ERR! stack     at require (internal/module.js:11:18)
node-pre-gyp ERR! stack     at evalmachine.<anonymous>:36:16
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/Administrator/Documents/tilestream/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/fs.js:11:8)
node-pre-gyp ERR! stack     at Module._compile (module.js:624:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:635:10)
node-pre-gyp ERR! stack     at Module.load (module.js:545:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:508:12)
node-pre-gyp ERR! System Darwin 11.4.2
node-pre-gyp ERR! command "/Users/Administrator/.nvm/versions/node/v8.7.0/bin/node" "/Users/Administrator/Documents/tilestream/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Administrator/Documents/tilestream/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.22
```
