### ISSUE TITLE
Arguments like --dist-url/--nodedir not respected with npm 3.10.10

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-pre-gyp#300]
## Context

When someone runs `npm install --some-option` to install a module that uses `node-pre-gyp`, then `node-pre-gyp` notices the arguments passed and forwards to `node-gyp` (when a source compile is needed). The same thing is done when `node-pre-gyp` is called directly (rather than via npm). This argument forwarding is critical to be able to control `node-gyp` behavior directly (since modules that use `node-pre-gyp` don't directly call `node-gyp`, by design).

## Problem

This argument passing works in all cases when arguments are passed directly to `node-pre-gyp`. For example `node-pre-gyp build --dist-url=foo` will result in a call to `node-gyp build --dist-url=foo`.

And this argument passing works in all cases when arguments are passed to `npm` and `npm calls` `node-pre-gyp` except on windows with npm 3.10.10. What I've seen is:

 

|             | mac                | linux | windows | 
|-------------|--------------------|-------|---------|
| node v6/npm 3.10.10 | :white_check_mark: | :white_check_mark:  | :x: |
| node v6/npm 2.15.11 (downgraded)       | :white_check_mark: | :white_check_mark:  |  :white_check_mark:  |
| node v4/npm 2.15.11        |:white_check_mark: | :white_check_mark:  |  :white_check_mark:  |
| node v0.10/npm2.15.1       |:white_check_mark: | :white_check_mark:  |  :white_check_mark:  |

**Comment by springmeyer** [comment]
Looks like this bug also impacts npm 5.3.0 / node v8.4.0 on windows: https://ci.appveyor.com/project/Mapbox/node-pre-gyp/build/1.0.625/job/m02cx3p7chk0q4km#L53

And with those versions another problem manifests that looks like:

```
not ok 29 Error: Command failed 'npm install --clang=1 --msvs_version=2015 --fallback-to-build=false'
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: Command failed 'npm install --clang=1 --msvs_version=2015   --fallback-to-build=false']
    at: maybeClose (internal/child_process.js:927:16)
    stack: |-
      module.js:491
          throw err;
          ^
      
      Error: Cannot find module 'C:\projects\node-pre-gyp\test\app1\node_modules\node-pre-gyp\bin\node-pre-gyp'
          at Function.Module._resolveFilename (module.js:489:15)
          at Function.Module._load (module.js:439:25)
          at Function.Module.runMain (module.js:609:10)
          at startup (bootstrap_node.js:158:16)
          at bootstrap_node.js:598:3
      npm ERR! code ELIFECYCLE
      npm ERR! errno 1
      npm ERR! node-pre-gyp-test-app1@0.1.0 install: `node-pre-gyp install --fallback-to-build`
      npm ERR! Exit status 1
      npm ERR! 
      npm ERR! Failed at the node-pre-gyp-test-app1@0.1.0 install script.
      npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
      
      npm ERR! A complete log of this run can be found in:
      npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2017-09-08T16_49_52_844Z-debug.log
      
  ...
ok 30 should not be equal

```
https://ci.appveyor.com/project/Mapbox/node-pre-gyp/build/1.0.625/job/m02cx3p7chk0q4km#L112

**Comment by springmeyer** [comment]
I dig into this a bit more and have figured out why the tests are failing, but not yet how to fix. Here is what I've learned:

 - On unix with you can do `npm -C test/app1 install` and it will: a) change into the `test/app1` directory and install the tool.
 - On windows with `npm v2.x` it works the same as on unix
 - But on windows with `> npm v2.x` the `npm -C test/app1 install` behaves differently. Instead of attempting to install `app1` instead it installs `node-pre-gyp`.

The fact that it installs `node-pre-gyp` makes no sense to me given that `node-pre-gyp` is not a dependency of `test/app1` (it is not listed in the deps for that app). So I have no idea why this is happening.

But it is the cause of the test failures. What happens is that the tests expect `npm -C test/app1 install` to fail when an invalid argument is passed like `--nodedir=invalid-value`. But because that command just goes and installs `node-pre-gyp` it passes, which is super bizzarre.


Here is the output of `npm -C test/app1/ install` on windows with `npm 3.10.10`:

```
C:\projects\node-pre-gyp\test\app1\node-pre-gyp -> C:\projects\node-pre-gyp\test\app1\node_modules\node-pre-gyp\bin\node-pre-gyp
node-pre-gyp-test-app1@0.1.0 C:\projects\node-pre-gyp\test\app1
`-- node-pre-gyp@0.9.1 
  +-- detect-libc@1.0.3 
  +-- mkdirp@0.5.1 
  | `-- minimist@0.0.8 
  +-- needle@2.2.1 
  | +-- debug@2.6.9 
  | | `-- ms@2.0.0 
  | +-- iconv-lite@0.4.21 
  | | `-- safer-buffer@2.1.2 
  | `-- sax@1.2.4 
  +-- nopt@4.0.1 
  | +-- abbrev@1.1.1 
  | `-- osenv@0.1.5 
  |   +-- os-homedir@1.0.2 
  |   `-- os-tmpdir@1.0.2 
  +-- npm-packlist@1.1.10 
  | +-- ignore-walk@3.0.1 
  | | `-- minimatch@3.0.4 
  | |   `-- brace-expansion@1.1.11 
  | |     +-- balanced-match@1.0.0 
  | |     `-- concat-map@0.0.1 
  | `-- npm-bundled@1.0.3 
  +-- npmlog@4.1.2 
  | +-- are-we-there-yet@1.1.4 
  | | +-- delegates@1.0.0 
  | | `-- readable-stream@2.3.6 
  | |   +-- core-util-is@1.0.2 
  | |   +-- isarray@1.0.0 
  | |   +-- process-nextick-args@2.0.0 
  | |   +-- string_decoder@1.1.1 
  | |   `-- util-deprecate@1.0.2 
  | +-- console-control-strings@1.1.0 
  | +-- gauge@2.7.4 
  | | +-- aproba@1.2.0 
  | | +-- has-unicode@2.0.1 
  | | +-- object-assign@4.1.1 
  | | +-- signal-exit@3.0.2 
  | | +-- string-width@1.0.2 
  | | | +-- code-point-at@1.1.0 
  | | | `-- is-fullwidth-code-point@1.0.0 
  | | |   `-- number-is-nan@1.0.1 
  | | +-- strip-ansi@3.0.1 
  | | | `-- ansi-regex@2.1.1 
  | | `-- wide-align@1.1.2 
  | `-- set-blocking@2.0.0 
  +-- rc@1.2.7 
  | +-- deep-extend@0.5.1 
  | +-- ini@1.3.5 
  | +-- minimist@1.2.0 
  | `-- strip-json-comments@2.0.1 
  +-- rimraf@2.6.2 
  | `-- glob@7.1.2 
  |   +-- fs.realpath@1.0.0 
  |   +-- inflight@1.0.6 
  |   | `-- wrappy@1.0.2 
  |   +-- inherits@2.0.3 
  |   +-- once@1.4.0 
  |   `-- path-is-absolute@1.0.1 
  +-- semver@5.5.0 
  `-- tar@4.4.2 
    +-- chownr@1.0.1 
    +-- fs-minipass@1.2.5 
    +-- minipass@2.2.4 
    +-- minizlib@1.1.0 
    +-- safe-buffer@5.1.2 
    `-- yallist@3.0.2 
```

**Comment by springmeyer** [comment]
Hoping this will fix https://github.com/mapbox/node-pre-gyp/commit/9361b44b7f8348a50b5ad0ef57d9a6a8c2479e11

https://ci.appveyor.com/project/Mapbox/node-pre-gyp/build/1.0.770
