### ISSUE TITLE
node-pre-gyp broken on node v8 / windows

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-pre-gyp#302]
When testing node-pre-gyp on appveyor with node v8 (v8.0.0 specifically gets pulled in and npm 5.0.0), things are terribly broken. Not really dug much yet, but looks related to npm install not working:

```
     Error: Cannot find module 'nopt'
          at Function.Module._resolveFilename (module.js:485:15)
          at Function.Module._load (module.js:437:25)
          at Module.require (module.js:513:17)
          at require (internal/module.js:11:18)
          at Object.<anonymous> (C:\projects\node-pre-gyp\lib\node-pre-gyp.js:14:12)
          at Module._compile (module.js:569:30)
          at Object.Module._extensions..js (module.js:580:10)
          at Module.load (module.js:503:32)
          at tryModuleLoad (module.js:466:12)
          at Function.Module._load (module.js:458:3)
```

**Comment by springmeyer** [comment]
Could also be an appveyor oddity: appveyor reports `Installing node 8.1.0 (x64)...` but then next reports:

```
node --version
v8.0.0
npm --version
5.0.0
```

That seems off /cc @FeodorFitsner

Refs https://ci.appveyor.com/project/Mapbox/node-pre-gyp/build/1.0.581/job/933655r0ad6ehjrn#L7

**Comment by springmeyer** [comment]
Found this can be worked around by downgrading npm to `2.x`

**Comment by FeodorFitsner** [comment]
Oh, good catch with 8.1.0 package, thanks! It should be fixed now.
