### ISSUE TITLE
Build broken on node 8.1.1 / os x

### ISSUE THREAD

**Issue by tuananh** [mapbox/node-pre-gyp#305]
Not sure if this is node-pre-gyp issue. It works fine on node 8 and node 8.1 but failing on node 8.1.1

```
70 info lifecycle camaro@1.1.0~install: camaro@1.1.0
71 verbose lifecycle camaro@1.1.0~install: unsafe-perm in lifecycle true
72 verbose lifecycle camaro@1.1.0~install: PATH: /Users/anh/.npm/lib/node_modules/npm/bin/node-gyp-bin:/Users/anh/code/test/node_modules/camaro/node_modules/.bin:/Users/anh/code/test/node_modules/.bin:/Users/anh/.npm/bin:/usr/local/bin:/Users/anh/bin:/Users/anh/.rbenv/bin:/Users/anh/.gem/bin:/usr/local/opt/go/libexec/bin:/usr/local/go/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
73 verbose lifecycle camaro@1.1.0~install: CWD: /Users/anh/code/test/node_modules/camaro
74 silly lifecycle camaro@1.1.0~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
75 silly lifecycle camaro@1.1.0~install: Returned: code: 1  signal: null
76 info lifecycle camaro@1.1.0~install: Failed to exec install script
77 verbose unlock done using /Users/anh/.npm/_locks/staging-f9cbf1b153f2260d.lock for /Users/anh/code/test/node_modules/.staging
78 warn @goquo/test@1.0.0 No description
79 warn @goquo/test@1.0.0 No repository field.
80 verbose stack Error: camaro@1.1.0 install: `node-pre-gyp install --fallback-to-build`
80 verbose stack Exit status 1
80 verbose stack     at EventEmitter.<anonymous> (/Users/anh/.npm/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
80 verbose stack     at emitTwo (events.js:125:13)
80 verbose stack     at EventEmitter.emit (events.js:213:7)
80 verbose stack     at ChildProcess.<anonymous> (/Users/anh/.npm/lib/node_modules/npm/lib/utils/spawn.js:40:14)
80 verbose stack     at emitTwo (events.js:125:13)
80 verbose stack     at ChildProcess.emit (events.js:213:7)
80 verbose stack     at maybeClose (internal/child_process.js:897:16)
80 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
81 verbose pkgid camaro@1.1.0
82 verbose cwd /Users/anh/code/test
83 verbose Darwin 16.6.0
84 verbose argv "/usr/local/bin/node" "/Users/anh/.npm/bin/npm" "i" "camaro" "--build-from-source"
85 verbose node v8.1.1
86 verbose npm  v5.0.3
87 error code ELIFECYCLE
88 error errno 1
89 error camaro@1.1.0 install: `node-pre-gyp install --fallback-to-build`
89 error Exit status 1
90 error Failed at the camaro@1.1.0 install script.
90 error This is probably not a problem with npm. There is likely additional logging output above.
91 verbose exit [ 1, true ]
```

**Comment by tuananh** [comment]
apparently, issue with node https://github.com/nodejs/node/issues/13667
