### ISSUE TITLE
sqlite3 for arm linux with node version 0.12.7

### ISSUE THREAD

**Issue by maitreyi-timesys** [mapbox/node-pre-gyp#332]
I am trying to build sqlite3 with older node js v0.12.7 for xylinx board.

Getting following error on target

> node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v11-linux-arm.tar.gz
> node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v11-linux-arm.tar.gz
> node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v11-linux-arm.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@0.10.21 (node-v11 ABI, unknown) (falling back to source compile with node-gyp) 
> node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v11-linux-arm.tar.gz 
> gyp ERR! build error 
> gyp ERR! stack Error: not found: make
> gyp ERR! stack     at F (/opt/node/lib/node_modules/npm/node_modules/which/which.js:43:28)
> gyp ERR! stack     at E (/opt/node/lib/node_modules/npm/node_modules/which/which.js:46:29)
> gyp ERR! stack     at /opt/node/lib/node_modules/npm/node_modules/which/which.js:57:16
> gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
> gyp ERR! System Linux 4.1.38-master-magmon-dms-ba16+g5ba6790
> gyp ERR! command "/opt/node/bin/node" "/opt/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/root/node_modules/sqlite3/lib/binding/node-v11-l"
> gyp ERR! cwd /home/root/node_modules/sqlite3
> gyp ERR! node -v v0.10.21
> gyp ERR! node-gyp -v v0.10.10
> gyp ERR! not ok 
> node-pre-gyp ERR! build error 
> node-pre-gyp ERR! stack Error: Failed to execute '/opt/node/bin/node /opt/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/root/node_modules/sqlite)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/root/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
> node-pre-gyp ERR! stack     at maybeClose (child_process.js:735:16)
>

**Comment by thom-nic** [comment]
This is not strictly a node-pre-gyp issue.  First, the node-sqlite authors opt which architectures and platforms to publish pre-built binaries for.  I myself am running sw with node-sqlite on arm/linux and I pre-build several modules that don't have official published ARM binaries.

Second, the actual error is:
```
 gyp ERR! stack Error: not found: make
```

Install `make` or more likely, `build-essential`
