### ISSUE TITLE
" Cannot find module 'internal/util/types'" when installing sqlite3

### ISSUE THREAD

**Issue by christophe-riolo** [mapbox/node-pre-gyp#333]
I tried to install some software with npm that relied on sqlite3, not to avail because of the following error :

```
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: Cannot find module 'internal/util/types'
node-pre-gyp ERR! stack     at Function.Module._resolveFilename (module.js:542:15)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:472:25)
node-pre-gyp ERR! stack     at Module.require (module.js:585:17)
node-pre-gyp ERR! stack     at require (internal/module.js:11:18)
node-pre-gyp ERR! stack     at evalmachine.<anonymous>:31:26
node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/prey/node_modules/graceful-fs/fs.js:11:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:641:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:652:10)
node-pre-gyp ERR! stack     at Module.load (module.js:560:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:503:12)
node-pre-gyp ERR! System Linux 4.13.12-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/prey/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/prey/node_modules/sqlite3
node-pre-gyp ERR! node -v v9.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
```

I am not familiar enough with the internals of npm to be more helpful, but if you need any additional information do ask :)

**Comment by springmeyer** [comment]
Is this replicable if you do a fully clean install?

```
cd /usr/lib/node_modules/prey/
rm -rf node_modules
npm install
```

Does it happen again? Does it happen everytime? Does it happen if you downgrade to node v8?

**Comment by christophe-riolo** [comment]
`cd /usr/lib/node_modules/prey/` -> does not exist yet, I could never install it so far. However : 
```
mkdir /tmp/fresh
cd /tmp/fresh
npm install prey
```
did *not* yield the error, only when trying to install with -g flag.

It does happen everytime (I tried several times, both with sudo and logging as root, juste in case *something* weird happened)

Downgrading to node v8 did not solve the issue : 
```
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: Cannot find module 'internal/util/types'
node-pre-gyp ERR! stack     at Function.Module._resolveFilename (module.js:513:15)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:463:25)
node-pre-gyp ERR! stack     at Module.require (module.js:556:17)
node-pre-gyp ERR! stack     at require (internal/module.js:11:18)
node-pre-gyp ERR! stack     at evalmachine.<anonymous>:31:26
node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/prey/node_modules/graceful-fs/fs.js:11:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:612:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:623:10)
node-pre-gyp ERR! stack     at Module.load (module.js:531:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:494:12)
node-pre-gyp ERR! System Linux 4.13.12-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/prey/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/prey/node_modules/sqlite3
node-pre-gyp ERR! node -v v8.8.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
```

**Comment by thatgeek95** [comment]
Also running into this issue, any updates on a sustainable solution?

**Comment by PTS93** [comment]
Having the same issue on Ubuntu 17.04 with latest node and npm.

**Comment by Ronniep7** [comment]
having the same problam

**Comment by aleksander351** [comment]
same problem here

**Comment by Piratmac** [comment]
Hello,

I have exactly the same problem on Fedora 27, with node v8.9.4, npm npm v5.6.0 and node-pre-gyp -v v0.6.39. The local install works, not the global one (both done as root).

Out of curiosity, I tried to install sqlite3 directly.
The result:
npm install -g sqlite3@3.1.13
> sqlite3@3.1.13 install /usr/lib/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build
> node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v57-linux-x64.tar.gz 
> node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@8.9.4 (node-v57 ABI) (falling back to source compile with node-gyp) 
> gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.9.4"
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/sqlite3/.node-gyp"
> gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/sqlite3/.node-gyp/8.9.4"
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/sqlite3/.node-gyp"
> gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/sqlite3/.node-gyp/8.9.4"
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/sqlite3/.node-gyp"

I don't understand how root could not have access to a folder (maybe because that folder doesn't exist), and I don't know if it's related.


Regards,
Piratmac
