### ISSUE TITLE
Not able to build libxmljs

### ISSUE THREAD

**Issue by skumar568** [mapbox/node-pre-gyp#339]
Getting below error:-
```
[centos@ip-172-21-42-12 LEAP]$ sudo npm i libxmljs

> libxmljs@0.18.4 install /home/centos/lmStubDocker/LEAP/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for libxmljs@0.18.4 and node@6.12.0 (node-v48 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmljs/libxmljs/releases/download/v0.18.4/node-v48-linux-x64.tar.gz
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/.node-gyp"
gyp http GET https://nodejs.org/download/release/v6.12.0/node-v6.12.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v6.12.0/node-v6.12.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v6.12.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v6.12.0/SHASUMS256.txt
make: Entering directory `/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build'
make: *** No rule to make target `../.node-gyp/6.12.0/include/node/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build/Release"
gyp ERR! cwd /home/centos/lmStubDocker/LEAP/node_modules/libxmljs
gyp ERR! node -v v6.12.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/centos/lmStubDocker/LEAP/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Linux 3.10.0-693.11.1.el7.x86_64
node-pre-gyp ERR! command "/usr/bin/node" "/home/centos/lmStubDocker/LEAP/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd /home/centos/lmStubDocker/LEAP/node_modules/libxmljs
node-pre-gyp ERR! node -v v6.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build/Release/xmljs.node --module_name=xmljs --module_path=/home/centos/lmStubDocker/LEAP/node_modules/libxmljs/build/Release' (1)
npm WARN vfleap@0.0.1 No license field.
npm ERR! Linux 3.10.0-693.11.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "i" "libxmljs"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! libxmljs@0.18.4 install: `node-pre-gyp install --fallback-to-build --loglevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.18.4 install script 'node-pre-gyp install --fallback-to-build --loglevel http'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libxmljs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --loglevel http
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs libxmljs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls libxmljs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/centos/lmStubDocker/LEAP/npm-debug.log
```
This is on Centos7 machine.

Thanks,
Sanjeev

**Comment by springmeyer** [comment]
This is a libxmljs issue. Please file a report at their repo.
