### ISSUE TITLE
node-gyp failure with npm 5.6.0, node 8.11.0, node-gyp 3.2.1 centos os 7

### ISSUE THREAD

**Issue by ntlzz93** [mapbox/node-pre-gyp#363]
```
node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@8.11.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home2/cuongle/Project/money-lover-test-backend/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home2/cuongle/.node-gyp/8.11.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home2/cuongle/.node-gyp/8.11.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home2/cuongle/Project/money-lover-test-backend',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /home2/cuongle/Project/money-lover-test-backend) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-696.20.1.el6.x86_64
gyp ERR! command "/home2/cuongle/.nvm/versions/node/v8.11.0/bin/node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /home2/cuongle/Project/money-lover-test-backend
gyp ERR! node -v v8.11.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
```

**Comment by springmeyer** [comment]
This error does not look like it has anything to do with node-pre-gyp. Rather it appears that you are running `node-gyp` (which is a different command https://github.com/nodejs/node-gyp) for a module that does not need to be built with `node-gyp`. HINT: `node-gyp` only works with modules that have a `binding.gyp` in their directory.
