### ISSUE TITLE
Error compiling fsevents?

### ISSUE THREAD

**Issue by jedahan** [mapbox/node-pre-gyp#370]
Not sure where to file this, but it looks like node-pre-gyp tries to compile node-serialport v4.0.7, which fails on node v10. When I created a new project with only node-serialport v6, it worked. Any suggestions?

```
// SNIP from npm install ava (which depends on chokidar, which depends on fsevents, which does this)
> fsevents@1.2.2 install /Volumes/data/code/living-room/service-js/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.2/fse-v1.2.2-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.2.2 and node@10.0.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /Volumes/data/code/living-room/service-js/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp

> serialport@4.0.7 install /Volumes/data/code/living-room/service-js/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/Cellar/node/10.0.0/bin/node',
node-pre-gyp verb cli   '/Volumes/data/code/living-room/service-js/node_modules/serialport/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@10.0.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Volumes/data/code/living-room/service-js/node_modules/serialport/build/Release/serialport.node" (not found)
node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for serialport@4.0.7 and node@10.0.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/4.0.7/serialport-v4.0.7-node-v64-darwin-x64.tar.gz
...SNIP...
9 warnings and 10 errors generated.
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Volumes/data/code/living-room/service-js/node_modules/serialport/build/Release/serialport.node" "--module_name=serialport" "--module_path=/Volumes/data/code/living-room/service-js/node_modules/serialport/build/Release"
gyp ERR! cwd /Volumes/data/code/living-room/service-js/node_modules/serialport
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by nicolasnoble** [comment]
That problem really is with fsevents, not with node-pre-gyp, as they haven't published node 10 binaries yet.

**Comment by springmeyer** [comment]
> That problem really is with fsevents, not with node-pre-gyp, as they haven't published node 10 binaries yet.

Correct, please report to fsevents repo.
