### ISSUE TITLE
Unable to run binaries using node-pre-gyp 

### ISSUE THREAD

**Issue by benmouh** [mapbox/node-pre-gyp#387]
I used node-pre-gyp to deploy c++ node addon, when I'm installing the binaries I got a dlopen error : 

```
$ node test.js
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: \\?\C:\Users\Lhousaine\Desktop\nodeAddons\test\node_modules\wakanda-stora
ge\bin\wakanda_storage.node nest pas une application Win32 valide.
\\?\C:\Users\Lhousaine\Desktop\nodeAddons\test\node_modules\wakanda-storage\bin\
wakanda_storage.node
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Lhousaine\Desktop\nodeAddons\test\node_modul
es\wakanda-storage\lib\index.js:4:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

```
any suggestion about the source of this problem

**Comment by VincentCheng34** [comment]
What is your node version?
I changed node version to v8.11.4, it worked for me on Mac system.
