### ISSUE TITLE
node-pre-gyp cant download pre-built binaries

### ISSUE THREAD

**Issue by stevensnoeijen** [mapbox/node-pre-gyp#412]
Im using a Macbook Pro Mid 2015 with MacOS High Sierra 10.13.6 with node v10.8.0 and npm 6.2.0
I wanted to install https://github.com/mapbox/tilelive-mapnik but this gives the error.
Then I tried to install node-mapnik seperatly on, I also get the same error.
Tried to install mapnik on an older version (8.9.4) of node but this works!

The error:
```
Stevens-MacBook-Pro:tilelive-test stevensnoeijen$ npm install mapnik
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason

> mapnik@3.7.2 install /Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v64-darwin-x64-Release.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@10.8.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v64-darwin-x64-Release.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@10.8.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik/lib/binding"
gyp ERR! cwd /Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
gypnode-pre-gyp ERR!  build error 
ERR! configure error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik/lib/binding' (1)
node-pre-gyp ERR! gypstack     at ChildProcess.<anonymous> (/Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
 node-pre-gyp ERR!ERR! stack     at ChildProcess.emit (events.js:182:13)
 stack Error: `gyp` failed with exit code: 1
node-pre-gypgyp  ERR!ERR!  stackstack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
     at maybeClose (internal/child_process.js:962:16)
gypnode-pre-gyp  ERR!ERR!  stackstack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
node-pre-gyp ERR!gyp System  Darwin 17.7.0
ERR! Systemnode-pre-gyp Darwin 17.7.0
 ERR! command "/usr/local/bin/node" "/Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
gypnode-pre-gyp  ERR!ERR!  cwdcommand /Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik
 "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik/lib/binding"
node-pre-gyp ERR!gyp  node -v v10.8.0
ERR! cwdnode-pre-gyp /Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik
 ERR!gyp  node-pre-gyp -vERR! v0.6.39
 node -vnode-pre-gyp v10.8.0
 ERR!gyp  not ok 
ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/Users/stevensnoeijen/Downloads/tilelive-test/node_modules/@mapbox/tilelive-mapnik/node_modules/mapnik/lib/binding' (1)
npm WARN tilelive-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@3.7.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@3.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stevensnoeijen/.npm/_logs/2018-08-15T12_40_58_654Z-debug.log
```

the log file https://pastebin.com/3GXfTbTR

duplicate issue at https://github.com/mapnik/node-mapnik/issues/895, but I guess the issue belongs here..

**Comment by springmeyer** [comment]
closed over at https://github.com/mapnik/node-mapnik/issues/895#issuecomment-413554215
