### ISSUE TITLE
Please fix install errors

### ISSUE THREAD

**Issue by molerat619** [mapbox/node-pre-gyp#419]
Hey there!

I know there have been various issues regarding this.

I have problems running `npm install` on my project that has a dependency that depends on node-pre-gyp. It always fails when trying to install node-pre-gyp. I have tried it with many different node/npm versions using nvm (from  4 - 10). I have gone through all suggestions of #413 #381 #367 and many more + stackoverflow and I have spent way too many, many hours trying to resolve this.

Please fix the install or explain how this can be easily fixed. With all due respect, this is really a pain.

Here is an example log of where it fails right now.

```
Marcels-MBP-2:project myuser$ npm install

> v8-debug@0.4.2 install /Applications/XAMPP/xamppfiles/htdocs/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/Users/myuser/.nvm/versions/node/v10.12.0/bin/node',
node-pre-gyp verb cli   '/Applications/XAMPP/xamppfiles/htdocs/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.4
node-pre-gyp info using node@10.12.0 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Applications/XAMPP/xamppfiles/htdocs/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.2/node-v64-darwin-x64/debug.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/debug/v0.4.2/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: Cannot find module 'internal/util/types'
node-pre-gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
node-pre-gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:636:17)
node-pre-gyp ERR! stack     at require (internal/modules/cjs/helpers.js:20:18)
node-pre-gyp ERR! stack     at evalmachine.<anonymous>:44:31
node-pre-gyp ERR! stack     at Object.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/fs.js:11:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:688:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:598:32)
node-pre-gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/Users/myuser/.nvm/versions/node/v10.12.0/bin/node" "/Applications/XAMPP/xamppfiles/htdocs/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Applications/XAMPP/xamppfiles/htdocs/project/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v10.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! v8-debug@0.4.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the v8-debug@0.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by pierrebonbon** [comment]
Getting the exact same thing when attempting to install tilelive-modules or tessera. Tried everything, from different node versions to reinstalling node-pre-gyp and updating it. No luck as yet.

**Comment by okomaro** [comment]
I have the same error. Check on another mac, it gave same problems. seems like a bug.

**Comment by asantiago323** [comment]
This is a long and drawn out issue it seems. I have been trying to get firebase installed, but cannot due to this same issue. I am using node v10.13, so there shouldn't be any issues, since they mentioned that grpc@1.16 should have fixed the node-pre-gyp install bug.

😞
