### ISSUE TITLE
node 11 support

### ISSUE THREAD

**Issue by nicolasnoble** [mapbox/node-pre-gyp#421]
Node 11 has been released a couple of days ago, and trying to build node-pre-gyp-enabled packages with it lead to the typical error of "Unsupported target version".

```
+ ./node_modules/.bin/node-pre-gyp configure rebuild package --target=11.0.0 --target_arch=ia32
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@10.12.0 | darwin | x64
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: Unsupported target version: 11.0.0
node-pre-gyp ERR! stack     at get_runtime_abi (/Volumes/BuildData/tmpfs/src/github/grpc-node/packages/grpc-native-core/node_modules/node-pre-gyp/lib/util/versioning.js:173:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Volumes/BuildData/tmpfs/src/github/grpc-node/packages/grpc-native-core/node_modules/node-pre-gyp/lib/util/versioning.js:295:19)
node-pre-gyp ERR! stack     at handle_gyp_opts (/Volumes/BuildData/tmpfs/src/github/grpc-node/packages/grpc-native-core/node_modules/node-pre-gyp/lib/util/handle_gyp_opts.js:60:27)
node-pre-gyp ERR! stack     at configure (/Volumes/BuildData/tmpfs/src/github/grpc-node/packages/grpc-native-core/node_modules/node-pre-gyp/lib/configure.js:12:5)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as configure] (/Volumes/BuildData/tmpfs/src/github/grpc-node/packages/grpc-native-core/node_modules/node-pre-gyp/lib/node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack     at run (/Volumes/BuildData/tmpfs/src/github/grpc-node/packages/grpc-native-core/node_modules/node-pre-gyp/bin/node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Volumes/BuildData/tmpfs/src/github/grpc-node/packages/grpc-native-core/node_modules/node-pre-gyp/bin/node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:688:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:598:32)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/Users/kbuilder/.nvm/versions/node/v10.12.0/bin/node" "/Volumes/BuildData/tmpfs/src/github/grpc-node/packages/grpc-native-core/node_modules/.bin/node-pre-gyp" "configure" "rebuild" "package" "--target=11.0.0" "--target_arch=ia32"
node-pre-gyp ERR! cwd /Volumes/BuildData/tmpfs/src/github/grpc-node/packages/grpc-native-core
node-pre-gyp ERR! node -v v10.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>;
```

**Comment by lissyx** [comment]
I'm also interested in that
