### ISSUE TITLE
UNCAUGHT EXCEPTION - Error: spawn EPERM

### ISSUE THREAD

**Issue by GongT** [mapbox/node-pre-gyp#424]
Error while installing `lzma-native` for `electron` with `yarn`:
```
error X:\kendryte ide\.release\kendryte-ide-release-x64\node_modules\lzma-native: Command failed.
Exit code: 7
Command: node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build
Arguments:
Directory: X:\kendryte ide\.release\kendryte-ide-release-x64\node_modules\lzma-native
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@8.11.2 | win32 | x64
node-pre-gyp info check checked for "X:\kendryte ide\.release\kendryte-ide-release-x64\node_modules\lzma-native\binding-v3.0.8-electron-v2.0-win32-x64\lzma_native.node" (not found)
node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-electron-v2.0-win32-x64.tar.gz
node-pre-gyp http 404 https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-electron-v2.0-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-electron-v2.0-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.8 and electron@2.0.12 (electron-v2.0 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-electron-v2.0-win32-x64.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: spawn EPERM
node-pre-gyp ERR! stack     at _errnoException (util.js:992:11)
node-pre-gyp ERR! stack     at ChildProcess.spawn (internal/child_process.js:323:11)
node-pre-gyp ERR! stack     at Object.exports.spawn (child_process.js:502:9)
node-pre-gyp ERR! stack     at Object.module.exports.run_gyp (X:\kendryte ide\.release\kendryte-ide-release-x64\node_modules\node-pre-gyp\lib\util\compile.js:74:18)
node-pre-gyp ERR! stack     at build (X:\kendryte ide\.release\kendryte-ide-release-x64\node_modules\node-pre-gyp\lib\build.js:33:17)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as build] (X:\kendryte ide\.release\kendryte-ide-release-x64\node_modules\node-pre-gyp\lib\node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (X:\kendryte ide\.release\kendryte-ide-release-x64\node_modules\node-pre-gyp\bin\node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:131:7)
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:180:9)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "X:\\kendryte ide\\.release\\FAKE_HOME\\nodejs\\node.exe" "X:\\kendryte ide\\.release\\kendryte-ide-release-x64\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd X:\kendryte ide\.release\kendryte-ide-release-x64\node_modules\lzma-native
node-pre-gyp ERR! node -v v8.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by towfiqi** [comment]
Same issue here. Did you find any solution?
