### ISSUE TITLE
Require('node-pre-gyp') give void object in sqlite3.js, node.js,  Raspberry

### ISSUE THREAD

**Issue by ivleneb** [mapbox/node-pre-gyp#429]
**I have the next error in node.js with sqlite3 when trying to execute some js script:**
"
/usr/local/lib/node_modules/sqlite3/lib/sqlite3.js:4
var binding_path = binary.find(path.resolve(path.join(__dirname,'../package.json')));
                          ^
TypeError: binary.find is not a function
"
**Checking more deeply, i found:**
"
// File /usr/local/lib/node_modules/sqlite3/lib/sqlite3.js
var binary = require('node-pre-gyp');
console.log(binary) ; // **I put this, and it displays: {}**
var path = require('path');
var binding_path = binary.find(path.resolve(path.join(__dirname,'../package.json'))); // **And here is the error**

"
**In _/usr/local/lib/node_modules/sqlite3/node_modules/node-pre-gyp_, when using the command _testpackage_  (https://www.npmjs.com/package/node-pre-gyp), i got:** 
"
root@openHABianPi:/usr/local/lib/node_modules/sqlite3/node_modules/node-pre-gyp# node-pre-gyp testpackage

node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@10.13.0 | linux | arm
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: node-pre-gyp package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties: 
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (/usr/local/lib/node_modules/node-pre-gyp/lib/util/versioning.js:220:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/usr/local/lib/node_modules/node-pre-gyp/lib/util/versioning.js:279:5)
node-pre-gyp ERR! stack     at testpackage (/usr/local/lib/node_modules/node-pre-gyp/lib/testpackage.js:20:27)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as testpackage] (/usr/local/lib/node_modules/node-pre-gyp/lib/node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack     at run (/usr/local/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:688:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:598:32)
node-pre-gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
node-pre-gyp ERR! System Linux 4.14.70-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-pre-gyp" "testpackage"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/sqlite3/node_modules/node-pre-gyp
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues

"

**So I think that may be a bug is there.
Help please!**

npm -v
6.4.1
node -v
v10.13.1
OS openhabian, Raspberry Pi 3

**Comment by castarco** [comment]
Same here, two years later, with the new `@mapbox/node-pre-gyp` package. Although indirectly.

I just run `yarn upgrade`, and some dependencies were upgraded, but none of them were direct "consumers" of `@mapbox/node-pre-gyp` or `@mapbox/node-pre-gyp` itself.

Then it started failing when importing some packages that seem to depend on it.

I'm sorry I can't give more information than that. I used the IDE's (VSCode) capabilities to navigate through the code, and the `find` function was there (as a function, not any other thing), so I can't understand why it fails saying that `find` is not a function.
