### ISSUE TITLE
Err on node-pregpy

### ISSUE THREAD

**Issue by Artis84** [mapbox/node-pre-gyp#440]
```
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: Cannot find module 'internal/util/types'
node-pre-gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
node-pre-gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:637:17)
node-pre-gyp ERR! stack     at require (internal/modules/cjs/helpers.js:22:18)
node-pre-gyp ERR! stack     at evalmachine.<anonymous>:44:31
node-pre-gyp ERR! stack     at Object.<anonymous> (C:\Users\Jacques\Desktop\DQJSN\server\node_modules\sqlite3\node_modules\node-pre-gyp\node_modules\tar\node_modules\fstream\node_modules\graceful-fs\fs.js:11:8)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:689:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:599:32)
node-pre-gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jacques\\Desktop\\DQJSN\\server\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Jacques\Desktop\DQJSN\server\node_modules\sqlite3
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.22
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN sqlite3@2.2.7 had bundled packages that do not match the required version(s). They have been replaced with non-bundled versions.
npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
I have this issue since 1 week and i can t fix it.

**Done:**
npm rebuild
install node-pre-gpy
install node-gpy

version of node: v10.15.0

Thanks for your help:)

**Comment by BengBu-YueZhang** [comment]
me too

**Comment by Dionysusnu** [comment]
Same issue
