### ISSUE TITLE
node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by yingyi-ma** [mapbox/node-pre-gyp#471]
```
npm WARN prefer global node-gyp@3.8.0 should be installed with -g

> node-libcurl@1.3.3 install /opt/ClusterODM/node_modules/node-libcurl
> node-pre-gyp install `--fallback-to-build`

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack TypeError: this is not a typed array.
node-pre-gyp ERR! stack     at Function.from (native)
node-pre-gyp ERR! stack     at Object.<anonymous> (/opt/ClusterODM/node_modules/node-libcurl/node_modules/node-pre-gyp/node_modules/tar/lib/parse.js:33:27)
node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
node-pre-gyp ERR! stack     at Module.load (module.js:344:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:301:12)
node-pre-gyp ERR! stack     at Module.require (module.js:354:17)
node-pre-gyp ERR! stack     at require (internal/module.js:12:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/opt/ClusterODM/node_modules/node-libcurl/node_modules/node-pre-gyp/node_modules/tar/lib/list.js:10:16)
node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
node-pre-gyp ERR! System Linux 4.4.0-116-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/opt/ClusterODM/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/ClusterODM/node_modules/node-libcurl
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! Linux 4.4.0-116-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@1.3.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the node-libcurl@1.3.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-libcurl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/ClusterODM/npm-debug.log
```

**Comment by yingyi-ma** [comment]
**Help!**[](url)

**Comment by GtaMasterYT** [comment]
Same issue.

**Comment by yingyi-ma** [comment]
> Same issue.

Try using the latest nodejs.

**Comment by ivy7647** [comment]
I'm already using the latest nodejs, still having similar issue with below error:

`> fsevents@1.2.9 install /xxx/node_modules/karma/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! Completion callback never invoked! 
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/xxx/node_modules/karma/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /xxx/node_modules/karma/node_modules/fsevents
node-pre-gyp ERR! node -v v10.16.2
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not h`

Please help!

**Comment by vishalchavanvicky** [comment]
This is because of npm is not compatible.
Try to update npm to latest version by

'npm update'

Thank you

**Comment by yyforever0608** [comment]
E:\project1\main2>npm update

E:\project1\main2>npm install

> worker-by-electron-main@1.0.0 postinstall E:\project1\main2
> electron-builder install-app-deps

  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=win32 arch=x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> sqlite3@4.1.0 install E:\project1\main2\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

**Comment by vishalchavanvicky** [comment]
Error: C:\Program Files\nodejs\node.exe exited with code 1

According to error , Node is not detected  ,you should first Install Node.js in your system.

**Comment by vikjdk7** [comment]
Did we find any solution ? I have same error while deploying my microservice to cloudfoundry. I updated my npm, I installed sqlite3@4.1.0, but no success 

![image](https://user-images.githubusercontent.com/13382923/65600530-e678cc00-dfbd-11e9-99b3-9f4c65a8af84.png)

**Comment by vikjdk7** [comment]
> Did we find any solution ? I have same error while deploying my microservice to cloudfoundry. I updated my npm, I installed sqlite3@4.1.0, but no success
> 
> ![image](https://user-images.githubusercontent.com/13382923/65600530-e678cc00-dfbd-11e9-99b3-9f4c65a8af84.png)

I fixed the issue :) 
for me it was sqlite node module incorrect installation.
I removed it from package.json file and did  npm install sqlite3 --no-save and then tried deploying it again. Worked for me

**Comment by jackbilesisdm** [comment]
Was having a similar issue and can confirm removing the module name form the `package.json` and reinstalling will prevent this issue.

**Comment by Rana53** [comment]
i also face same problem.i found solution for that.
bcrypt required C++, python and node-pre-gyp.
    sudo apt-get install g++
    sudo apt-get install -y build-essential python
    npm install node-pre-gyp
for more details check : https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#ubuntu-and-derivatives---elementary-linux-mint-etc

**Comment by alihesari** [comment]
@Rana53 Thank you. This work for me.

**Comment by WarenGonzaga** [comment]
@Rana53 it works!

**Comment by tirmey** [comment]
Thanks, Rana53! But for me it only works on mint 20 with the  --unsafe-perm=true param:
**npm install node-pre-gyp --unsafe-perm=true**

**Comment by mrsarm** [comment]
Having the same issue, @Rana53, @vikjdk7 and @tirmey workarounds didn't work for me. Tried with latest Npm installed in different Node versions: v8.17.0, v12.19.0 and v14.16.0.

I have Ubuntu 20.04 x64, with Python 2.7.18, and g++ 9.3.0.
