### ISSUE TITLE
node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by praveen049** [mapbox/node-pre-gyp#475]
When installing Hue, the npm fails on node-pre-gyp

below is the error message:

> zipfile@0.5.12 install /home/hadoop/hue/node_modules/zipfile
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack TypeError: this is not a typed array.
node-pre-gyp ERR! stack     at Function.from (native)
node-pre-gyp ERR! stack     at Unzip.write (/home/hadoop/hue/node_modules/minizlib/index.js:277:42)
node-pre-gyp ERR! stack     at Unpack.write (/home/hadoop/hue/node_modules/tar/lib/parse.js:305:58)
node-pre-gyp ERR! stack     at Request.ondata (stream.js:31:26)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! stack     at Request.emit (events.js:169:7)
node-pre-gyp ERR! stack     at IncomingMessage.<anonymous> (/home/hadoop/hue/node_modules/request/request.js:1080:12)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! stack     at IncomingMessage.emit (events.js:169:7)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:146:16)
node-pre-gyp ERR! System Linux 4.4.0-122-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/hadoop/hue/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/hadoop/hue/node_modules/zipfile
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN install:zipfile@0.5.12 zipfile@0.5.12 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:zipfile@0.5.12 Exit status 7

> libxmljs@0.19.5 install /home/hadoop/hue/node_modules/libxmljs
> node-pre-gyp install --fallback-to-build --loglevel http

Here are the npm and node version
> npm -v
3.5.2

> node -v
v4.2.6

This is similar to another issue : https://github.com/mapbox/node-pre-gyp/issues/471 which is still open, though the exception is different.

Can you help.

Thanks

**Comment by CarlomagnoLopez** [comment]
Hi, 

I have faced with the same problem, but in my case, I have to update npm and node js to latest versions then you need to be sure that you installed 

`npm install -g windows-build-tools`

after it, I used this: 

1 `npm install -g node-gyp`

2 `npm install bcrypt`

3 `npm install node-pre-gyp`

It works for me,

Have fun!!

CLC
