### ISSUE TITLE
Fresh Node install: Error: Cannot find module 'internal/util/types'

### ISSUE THREAD

**Issue by Rockster160** [mapbox/node-pre-gyp#538]
Been battling this issue for a while now- Trying to run `npm install -g esp8266`

I've searched all over, but all I'm seeing is suggestions to clear Node cache, clear modules, etc. 
I've tried removing the `node_modules` folders, running `npm update`, then trying again. I've completely abolished node from my entire system and started from scratch through NVM and gotten the same error. I've tried removing `package-lock.json`, downgrading to other Node versions, installing various other dependencies, but it's all to no avail- I keep getting the same error. Nothing changes. 

Running MacOS Big Sur
Node versions: various, but mostly 10.23 and 12.15. Tried downgrading to 6.x and 8.x as well, but nothing changed.

Full error is below. Has anybody found a workaround for this that's been in the same situation?

```
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/Users/username/.nvm/versions/node/v10.23.1/bin/esp -> /Users/username/.nvm/versions/node/v10.23.1/lib/node_modules/esp8266/bin/cli.js

> serialport@1.7.4 install /Users/username/.nvm/versions/node/v10.23.1/lib/node_modules/esp8266/node_modules/serialport
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/Users/username/.nvm/versions/node/v10.23.1/bin/node',
node-pre-gyp verb cli   '/Users/username/.nvm/versions/node/v10.23.1/lib/node_modules/esp8266/node_modules/serialport/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.7
node-pre-gyp info using node@10.23.1 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Users/username/.nvm/versions/node/v10.23.1/lib/node_modules/esp8266/node_modules/serialport/build/serialport/v1.7.4/Release/node-v64-darwin-x64/serialport.node" (not found)
node-pre-gyp http GET https://node-serialport.s3.amazonaws.com/serialport/v1.7.4/Release/node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: Cannot find module 'internal/util/types'
node-pre-gyp ERR! stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
node-pre-gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:692:17)
node-pre-gyp ERR! stack     at require (internal/modules/cjs/helpers.js:25:18)
node-pre-gyp ERR! stack     at evalmachine.<anonymous>:44:31
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/username/.nvm/versions/node/v10.23.1/lib/node_modules/esp8266/node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/fs.js:11:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:778:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:653:32)
node-pre-gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
node-pre-gyp ERR! System Darwin 20.2.0
node-pre-gyp ERR! command "/Users/username/.nvm/versions/node/v10.23.1/bin/node" "/Users/username/.nvm/versions/node/v10.23.1/lib/node_modules/esp8266/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/username/.nvm/versions/node/v10.23.1/lib/node_modules/esp8266/node_modules/serialport
node-pre-gyp ERR! node -v v10.23.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! serialport@1.7.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the serialport@1.7.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2021-01-08T08_29_30_094Z-debug.log
```

**Comment by springmeyer** [comment]
I think the problem is likely that `esp8266` is installing a very old version of node-serialport. I recommend ticketing this problem at https://github.com/paulcuth/esp8266-cli/issues and if you don't get a response then forking https://github.com/paulcuth/esp8266-cli and trying to upgrade node-serialport.
