### ISSUE TITLE
Crash when trying to use electron-builder

### ISSUE THREAD

**Issue by ZeroByter** [mapbox/node-pre-gyp#558]
Hello!

I am trying to build me Electron (v11.2.2) using electron-builder (v20.44.4) with Node version v14.15.4.

When I run my `npm package` I get the following output:
```
  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • public/electron.js not found. Please see https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3
  • loaded parent configuration preset=react-cra
  • description is missed in the package.json appPackageFile=C:\NodeJS Projects\PinkishFlamingo\package.json
  • author is missed in the package.json appPackageFile=C:\NodeJS Projects\PinkishFlamingo\package.json
  • writing effective config file=dist\builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=x64
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> node-sass@4.14.1 install C:\NodeJS Projects\PinkishFlamingo\node_modules\node-sass
> node scripts/install.js

node-sass build Binary found at C:\NodeJS Projects\PinkishFlamingo\node_modules\node-sass\vendor\win32-x64-83\binding.node

> node-sass@4.14.1 postinstall C:\NodeJS Projects\PinkishFlamingo\node_modules\node-sass
> node scripts/build.js

Binary found at C:\NodeJS Projects\PinkishFlamingo\node_modules\node-sass\vendor\win32-x64-83\binding.node
Testing binary
Binary is fine

> bufferutil@4.0.3 install C:\NodeJS Projects\PinkishFlamingo\node_modules\bufferutil
> node-gyp-build


> canvas@2.6.1 install C:\NodeJS Projects\PinkishFlamingo\node_modules\canvas
> node-pre-gyp install --fallback-to-build

Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\NodeJS Projects\PinkishFlamingo\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\NodeJS Projects\PinkishFlamingo\node_modules\canvas\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v11.2' (1)

Error output:
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-electron-v11.2-win32-unknown-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and electron@11.2.2 (electron-v11.2 ABI, unknown) (falling back to source compile with node-gyp) 
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    options.duplicate_basename_check)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 139, in Load
    params['parallel'], params['root_targets'])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2783, in Load
    variables, includes, depth, check, True)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 392, in LoadTargetBuildFile
    includes, True, check)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 264, in LoadOneBuildFile
    aux_data, includes, check)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 301, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
  File "C:\Program Files\Python36\lib\encodings\cp1255.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9e in position 2516: character maps to <undefined>
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\NodeJS Projects\\PinkishFlamingo\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\NodeJS Projects\\PinkishFlamingo\\node_modules\\canvas\\build\\Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v11.2"
gyp ERR! cwd C:\NodeJS Projects\PinkishFlamingo\node_modules\canvas
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\NodeJS Projects\PinkishFlamingo\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\NodeJS Projects\PinkishFlamingo\node_modules\canvas\build\Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v11.2' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\NodeJS Projects\PinkishFlamingo\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.19041
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\NodeJS Projects\\PinkishFlamingo\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\NodeJS Projects\PinkishFlamingo\node_modules\canvas
node-pre-gyp ERR! node -v v14.15.4
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\מפלג 88\AppData\Roaming\npm-cache\_logs\2021-02-10T12_32_53_866Z-debug.log

    at ChildProcess.<anonymous> (C:\NodeJS Projects\PinkishFlamingo\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
From previous event:
    at _rebuild (C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at _installOrRebuild (C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\src\packager.ts:509:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\src\packager.ts:470:70)
    at C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\src\packager.ts:420:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\NodeJS Projects\PinkishFlamingo\node_modules\graceful-fs\graceful-fs.js:144:16
    at C:\NodeJS Projects\PinkishFlamingo\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:171:23)
From previous event:
    at Packager._build (C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at Packager.build (C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\NodeJS Projects\PinkishFlamingo\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\NodeJS Projects\PinkishFlamingo\node_modules\electron-builder\src\builder.ts:228:10)
    at C:\NodeJS Projects\PinkishFlamingo\node_modules\electron-builder\src\cli\cli.ts:49:19
```

Obviously it's unable to download the Canvas prebuilt for Electron, but I thought that might not really be a big deal if it would have been able to "falling back to source compile with node-gyp" but it also fails when trying to do that.

I tried Googling this and look all over the place but was never able to find any conclusive fix.
Any ideas?

Also, I wasn't sure if to post this error here or over at electron-builder GitHub, but seeing as the error occured with pre-gyp, decided to ask here...

**Comment by ZeroByter** [comment]
Quick update, I'm fairly certain now this is cause by me having non-English letters in a file path somewhere. Problem is I'm not really sure where/how to change the usage/installation path of Node packages.

**Comment by springmeyer** [comment]
There are two problems I see:


 - node-canvas is not providing prebuilt binaries for your platform + node version (this would be an issue in node-canvas that you can bring up at that repo whether it is supposed to work)
 - so the build falls back to a source compile which fails due to your path (this would be a node-gyp bug)

So, this does not have to do with node-pre-gyp as far as I can tell, so I'll close this issue.
