### ISSUE TITLE
How to fix problems install eror

### ISSUE THREAD

**Issue by DAFF-OP** [mapbox/node-pre-gyp#575]
node-pre-gyp ERR! Completion callback never invoked!
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\DAFFA\\discordbot\\WorkSpace-Extend\\node_modules\\canvas\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\DAFFA\discordbot\WorkSpace-Extend\node_modules\canvas
node-pre-gyp ERR! node -v v13.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.15.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN extend@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! canvas@2.7.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the canvas@2.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by springmeyer** [comment]
I recommend switching to an LTS version of node (either v10, v12, or v14). If you still hit problems them please report to node-canvas repo's issue queue.

**Comment by deepng** [comment]
@springmeyer  I am on v10 LTS version of node, but still face this issue, what should be done here?

```> realm@3.6.5 install /Users/deepak/Documents/vymo/react-app/node_modules/realm
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp ERR! Completion callback never invoked!
node-pre-gyp ERR! System Darwin 20.3.0
node-pre-gyp ERR! command "/Users/deepak/.nvm/versions/node/v10.24.0/bin/node" "/Users/deepak/Documents/vymo/react-app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/deepak/Documents/vymo/react-app/node_modules/realm
node-pre-gyp ERR! node -v v10.24.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
```

**Comment by deepng** [comment]
@springmeyer  I am using an LTS version of node and still get this issue, please help.

```
_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/deepak/Documents/vymo/react-app/node_modules/realm
gyp ERR! node -v v12.22.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/deepak/.nvm/versions/node/v12.22.1/bin/node /Users/deepak/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/deepak/Documents/vymo/react-app/node_modules/realm/compiled/node-v72_darwin_x64/realm.node --module_name=realm --module_path=/Users/deepak/Documents/vymo/react-app/node_modules/realm/compiled/node-v72_darwin_x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/deepak/Documents/vymo/react-app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Darwin 20.3.0
node-pre-gyp ERR! command "/Users/deepak/.nvm/versions/node/v12.22.1/bin/node" "/Users/deepak/Documents/vymo/react-app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/deepak/Documents/vymo/react-app/node_modules/realm
node-pre-gyp ERR! node -v v12.22.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/Users/deepak/.nvm/versions/node/v12.22.1/bin/node /Users/deepak/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/deepak/Documents/vymo/react-app/node_modules/realm/compiled/node-v72_darwin_x64/realm.node --module_name=realm --module_path=/Users/deepak/Documents/vymo/react-app/node_modules/realm/compiled/node-v72_darwin_x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
```

**Comment by lucien-kejl** [comment]
the same error
