### ISSUE TITLE
Cannot find binaries for installation on ARM machine

### ISSUE THREAD

**Issue by sri-vathsa** [mapbox/node-pre-gyp#577]
I am trying to install node-pre-gyp on AWS graviton2 instance and I am getting the following error.

```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.15.0
node-pre-gyp info using node@15.11.0 | linux | arm64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/home/ubuntu/gitpod/node_modules/grpc-tools/bin/grpc_tools.node" (not found)
node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc-tools/v1.10.0/linux-arm64.tar.gz
node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc-tools/v1.10.0/linux-arm64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc-tools/v1.10.0/linux-arm64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/ubuntu/gitpod/node_modules/node-pre-gyp/lib/install.js:142:27)
node-pre-gyp ERR! stack     at Request.emit (node:events:390:22)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/ubuntu/gitpod/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:378:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:636:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:502:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:378:20)
node-pre-gyp ERR! stack     at addChunk (node:internal/streams/readable:313:12)
node-pre-gyp ERR! stack     at readableAddChunk (node:internal/streams/readable:288:9)
node-pre-gyp ERR! System Linux 5.4.0-1038-aws
node-pre-gyp ERR! command "/usr/bin/node" "/home/ubuntu/gitpod/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /home/ubuntu/gitpod/node_modules/grpc-tools
node-pre-gyp ERR! node -v v15.11.0
```

**Comment by springmeyer** [comment]
This is a question for the grpc-tools developers and I we cannot help you in this repo. The issue is that the grpc-tools developers have not packaged arm binaries and this is  either because they don't support binaries for arm architectures at all or they have not published arm binaries for your node version.
