### ISSUE TITLE
Error  node-pre-gyp install

### ISSUE THREAD

**Issue by jmorelos96** [mapbox/node-pre-gyp#587]
```
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.17.0
node-pre-gyp info using node@14.16.1 | linux | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: project package.json is not node-pre-gyp ready:
node-pre-gyp ERR! stack package.json must declare these properties: 
node-pre-gyp ERR! stack binary.module_name
node-pre-gyp ERR! stack binary.module_path
node-pre-gyp ERR! stack binary.host
node-pre-gyp ERR! stack     at validate_config (/root/.nvm/versions/node/v14.16.1/lib/node_modules/node-pre-gyp/lib/util/versioning.js:220:15)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/root/.nvm/versions/node/v14.16.1/lib/node_modules/node-pre-gyp/lib/util/versioning.js:279:5)
node-pre-gyp ERR! stack     at install (/root/.nvm/versions/node/v14.16.1/lib/node_modules/node-pre-gyp/lib/install.js:241:31)
node-pre-gyp ERR! stack     at Object.self.commands.<computed> [as install] (/root/.nvm/versions/node/v14.16.1/lib/node_modules/node-pre-gyp/lib/node-pre-gyp.js:52:37)
node-pre-gyp ERR! stack     at run (/root/.nvm/versions/node/v14.16.1/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:82:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/root/.nvm/versions/node/v14.16.1/lib/node_modules/node-pre-gyp/bin/node-pre-gyp:134:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:1063:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
node-pre-gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:928:32)
node-pre-gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
node-pre-gyp ERR! System Linux 5.3.0-1020-gcp
node-pre-gyp ERR! command "/root/.nvm/versions/node/v14.16.1/bin/node" "/root/.nvm/versions/node/v14.16.1/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/html/project
node-pre-gyp ERR! node -v v14.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.17.0
node-pre-gyp ERR! not ok 
project package.json is not node-pre-gyp ready:
package.json must declare these properties: 
binary.module_name
binary.module_path
binary.host

```

**Comment by bmacnaughton** [comment]
1. what are you trying to install? whatever it is has not been setup to work with node-pre-gyp.
2. you will want to install @mapbox/node-pre-gyp to get a non-deprecated version.

but step 2 above won't matter until the package you intend to install is setup to use node-pre-gyp.

see https://github.com/mapbox/node-pre-gyp/blob/master/README.md for details.

**Comment by jmorelos96** [comment]
@bmacnaughton  I was trying to install bcrypt and i need to install that library, whatever i just installed an older version and it work, i dont know what happen' but i guess that it is the newer version that doesnt work properly.

**Comment by bmacnaughton** [comment]
if you have the specifics of the version that didn't work i'd like to work with them to get it updated.

thanks for getting back with me!
