### ISSUE TITLE
ENOENT: no such file or directory, rename 'build-tmp-napi-v3' -> 'build'

### ISSUE THREAD

**Issue by ishanuda** [mapbox/node-pre-gyp#610]
Hi, 
I am trying to build the sqlite3 native module for web-kit and it gives the following error.
Please help.

**command:**
`node-pre-gyp build --runtime=node-webkit --target=0.49.1 --target_arch=x64`

**Error:**
D:\repo\node-addon-example\node_modules\sqlite3>node-pre-gyp build --runtime=node-webkit --target=0.49.1 --target_arch=x64
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.5
node-pre-gyp info using node@14.17.1 | win32 | x64
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: ENOENT: no such file or directory, rename 'build-tmp-napi-v3' -> 'build'
node-pre-gyp ERR! stack     at Object.renameSync (fs.js:794:3)
node-pre-gyp ERR! stack     at Object.module.exports.swap_build_dir_in (D:\dev-tools\nvm\v14.17.1\node_modules\@mapbox\node-pre-gyp\lib\util\napi.js:179:8)     
node-pre-gyp ERR! stack     at D:\dev-tools\nvm\v14.17.1\node_modules\@mapbox\node-pre-gyp\lib\build.js:21:12
node-pre-gyp ERR! stack     at handle_gyp_opts (D:\dev-tools\nvm\v14.17.1\node_modules\@mapbox\node-pre-gyp\lib\util\handle_gyp_opts.js:101:10)
node-pre-gyp ERR! stack     at do_build (D:\dev-tools\nvm\v14.17.1\node_modules\@mapbox\node-pre-gyp\lib\build.js:13:3)
node-pre-gyp ERR! stack     at build (D:\dev-tools\nvm\v14.17.1\node_modules\@mapbox\node-pre-gyp\lib\build.js:49:12)
node-pre-gyp ERR! stack     at Object.self.commands.<computed> [as build] (D:\dev-tools\nvm\v14.17.1\node_modules\@mapbox\node-pre-gyp\lib\node-pre-gyp.js:86:37)
node-pre-gyp ERR! stack     at run (D:\dev-tools\nvm\v14.17.1\node_modules\@mapbox\node-pre-gyp\lib\main.js:81:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (D:\dev-tools\nvm\v14.17.1\node_modules\@mapbox\node-pre-gyp\lib\main.js:125:1)
node-pre-gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-pre-gyp ERR! System Windows_NT 10.0.19043
node-pre-gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "build" "--runtime=node-webkit" "--target=0.49.1" "--target_arch=x64"
node-pre-gyp ERR! cwd D:\repo\node-addon-example\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.17.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.5

**Setup:**
Node : v14.17.1
NPM: v6.14.13
node-gyp: v8.1.0
node-pre-gyp: v1.0.5
nw-gyp: v3.6.5
sqlite3: v5.0.2

Thank you very much

**Comment by ishanuda** [comment]
Ok the problem solved by setting the following.

npm config -g set msvs_version 2017
and Python version to 3.9

Closing the issue as the library compiled the sqlite3 native module with no error.
