### ISSUE TITLE
After yarn build i tried yarn install and theres an error with node-pre-gyp

### ISSUE THREAD

**Issue by bkkdigital** [mapbox/node-pre-gyp#626]
error /Users/ming/Desktop/CODING/metaplex-master/js/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /Users/ming/Desktop/CODING/metaplex-master/js/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.7
node-pre-gyp info using node@16.13.1 | darwin | arm64
node-pre-gyp info check checked for "/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@16.13.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-darwin-unknown-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@16.13.1 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@16.13.1 | darwin | arm64
gyp info find Python using Python version 2.7.18 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
(node:10963) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ming/Library/Caches/node-gyp/16.13.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ming/Library/Caches/node-gyp/16.13.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ming/Library/Caches/node-gyp/16.13.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/usr/local/bin/node" "/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd /Users/ming/Desktop/CODING/metaplex-master/js/node_modules/canvas
gyp ERR! node -v v16.13.1
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/ming/Desktop/CODING/metaplex-master/js/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Darwin 21.1.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/ming/Desktop/CODING/metaplex-master/js/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/ming/Desktop/CODING/metaplex-master/js/node_modules/canvas
node-pre-gyp ERR! node -v v16.13.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.7
node-pre-gyp ERR! not ok

**Comment by bkkdigital** [comment]
after i fix node-pre-gyp err this came up

error An unexpected error occurred: "EACCES: permission denied, unlink '/Users/ming/Desktop/CODING/metaplex-master/js/packages/cli/node_modules/.bin/bundlr'"

**Comment by k4psis** [comment]
Have the same problem, but do not have the solution
