### ISSUE TITLE
node-pre-gyp install fail when i install pulsar-client

### ISSUE THREAD

**Issue by semi-xi** [mapbox/node-pre-gyp#662]
| Info |  Note |
| - | - |
| System Info | Mac OS Monterey V12.4   Apple M1|
| Node Info | 14.15.0 |

when  i install `pulsar-client-node`，it  dependence this package. it was fail when it run  `node-pre-gyp install`. 
it has something errors like this:
```
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> pulsar-client@1.7.0-rc.0 install /Users/jim/work/pulsar-client-node
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.7.0-rc.0-node-v83-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for pulsar-client@1.7.0-rc.0 and node@14.15.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://pulsar.apache.org/docs/en/client-libraries-cpp/libpulsar-v1.7.0-rc.0-node-v83-darwin-x64.tar.gz 
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
env: python: No such file or directory
make: *** [Release/nothing.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jim/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/Users/jim/.nvm/versions/node/v14.15.0/bin/node" "/Users/jim/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/jim/work/pulsar-client-node/build/Release/libpulsar.node" "--module_name=libpulsar" "--module_path=/Users/jim/work/pulsar-client-node/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /Users/jim/work/pulsar-client-node
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/jim/.nvm/versions/node/v14.15.0/bin/node /Users/jim/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jim/work/pulsar-client-node/build/Release/libpulsar.node --module_name=libpulsar --module_path=/Users/jim/work/pulsar-client-node/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jim/work/pulsar-client-node/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Darwin 21.5.0
node-pre-gyp ERR! command "/Users/jim/.nvm/versions/node/v14.15.0/bin/node" "/Users/jim/work/pulsar-client-node/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/jim/work/pulsar-client-node
node-pre-gyp ERR! node -v v14.15.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.8
node-pre-gyp ERR! not ok 
Failed to execute '/Users/jim/.nvm/versions/node/v14.15.0/bin/node /Users/jim/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jim/work/pulsar-client-node/build/Release/libpulsar.node --module_name=libpulsar --module_path=/Users/jim/work/pulsar-client-node/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pulsar-client@1.7.0-rc.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pulsar-client@1.7.0-rc.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jim/.npm/_logs/2022-07-19T07_18_58_446Z-debug.log

```

how can i solve this problem

**Comment by springmeyer** [comment]
This is a problem with the `pulsar-client` and not `node-pre-gyp`. In this case the `pulsar-client` does not (yet) provide binaries for your node version/platform. And the fallback to a source compile is working as expected, except that you need all the dependencies for source compile. You are missing Python. See https://github.com/nodejs/node-gyp#configuring-python-dependency for more details.
